//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLog.TransactionalAPI.SDK.SalaryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryCodeStatus", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Common")]
    public enum SalaryCodeStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBase", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfSalary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.Salary))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAbsenceCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.AbsenceCode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfNormalWorkingTime))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTime))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTimeDay))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfHolidayCalendar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.HolidayCalendar))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAllowance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.Allowance))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken))]
    public partial class APIBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfSalary", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfSalary : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Salary[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Salary[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Salary", Namespace="http://api.timelog.com/services/salary/1_1")]
    [System.SerializableAttribute()]
    public partial class Salary : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeSystemTypes SalaryCodeSystemTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SalaryAccountFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FlexPositiveFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.SalaryAccountFactorEffectTypes SalaryAccountFactorEffectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSystemSalaryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SalaryCodeGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryAccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.TimeTrackingFormat TimeTrackingFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.SalarySpecificationTypes SalarySpecificationTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeSystemTypes SalaryCodeSystemType {
            get {
                return this.SalaryCodeSystemTypeField;
            }
            set {
                if ((this.SalaryCodeSystemTypeField.Equals(value) != true)) {
                    this.SalaryCodeSystemTypeField = value;
                    this.RaisePropertyChanged("SalaryCodeSystemType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double SalaryAccountFactor {
            get {
                return this.SalaryAccountFactorField;
            }
            set {
                if ((this.SalaryAccountFactorField.Equals(value) != true)) {
                    this.SalaryAccountFactorField = value;
                    this.RaisePropertyChanged("SalaryAccountFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double FlexPositiveFactor {
            get {
                return this.FlexPositiveFactorField;
            }
            set {
                if ((this.FlexPositiveFactorField.Equals(value) != true)) {
                    this.FlexPositiveFactorField = value;
                    this.RaisePropertyChanged("FlexPositiveFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.SalaryAccountFactorEffectTypes SalaryAccountFactorEffect {
            get {
                return this.SalaryAccountFactorEffectField;
            }
            set {
                if ((this.SalaryAccountFactorEffectField.Equals(value) != true)) {
                    this.SalaryAccountFactorEffectField = value;
                    this.RaisePropertyChanged("SalaryAccountFactorEffect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int SalaryCodeID {
            get {
                return this.SalaryCodeIDField;
            }
            set {
                if ((this.SalaryCodeIDField.Equals(value) != true)) {
                    this.SalaryCodeIDField = value;
                    this.RaisePropertyChanged("SalaryCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool IsSystemSalaryCode {
            get {
                return this.IsSystemSalaryCodeField;
            }
            set {
                if ((this.IsSystemSalaryCodeField.Equals(value) != true)) {
                    this.IsSystemSalaryCodeField = value;
                    this.RaisePropertyChanged("IsSystemSalaryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public System.Guid SalaryCodeGuid {
            get {
                return this.SalaryCodeGuidField;
            }
            set {
                if ((this.SalaryCodeGuidField.Equals(value) != true)) {
                    this.SalaryCodeGuidField = value;
                    this.RaisePropertyChanged("SalaryCodeGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int SalaryAccountID {
            get {
                return this.SalaryAccountIDField;
            }
            set {
                if ((this.SalaryAccountIDField.Equals(value) != true)) {
                    this.SalaryAccountIDField = value;
                    this.RaisePropertyChanged("SalaryAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.TimeTrackingFormat TimeTrackingFormat {
            get {
                return this.TimeTrackingFormatField;
            }
            set {
                if ((this.TimeTrackingFormatField.Equals(value) != true)) {
                    this.TimeTrackingFormatField = value;
                    this.RaisePropertyChanged("TimeTrackingFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.SalarySpecificationTypes SalarySpecificationType {
            get {
                return this.SalarySpecificationTypeField;
            }
            set {
                if ((this.SalarySpecificationTypeField.Equals(value) != true)) {
                    this.SalarySpecificationTypeField = value;
                    this.RaisePropertyChanged("SalarySpecificationType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class Request : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.RequestParameter[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.RequestParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceClass {
            get {
                return this.ServiceClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceClassField, value) != true)) {
                    this.ServiceClassField = value;
                    this.RaisePropertyChanged("ServiceClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfAbsenceCode", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfAbsenceCode : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.AbsenceCode[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.AbsenceCode[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbsenceCode", Namespace="http://api.timelog.com/services/salary/1_1")]
    [System.SerializableAttribute()]
    public partial class AbsenceCode : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid AbsenceCodeGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeForSalaryIntegrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FlexPositiveFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsTransferredToSalaryIntegrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SalaryAccountFactorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.SalaryAccountFactorEffectTypes SalaryAccountFactorEffectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalaryAccountIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.TimeTrackingFormat TimeTrackingFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AbsenceCodeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AbsenceCodeTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeductCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublicVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequireApprovalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid AbsenceCodeGuid {
            get {
                return this.AbsenceCodeGuidField;
            }
            set {
                if ((this.AbsenceCodeGuidField.Equals(value) != true)) {
                    this.AbsenceCodeGuidField = value;
                    this.RaisePropertyChanged("AbsenceCodeGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeForSalaryIntegration {
            get {
                return this.CodeForSalaryIntegrationField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeForSalaryIntegrationField, value) != true)) {
                    this.CodeForSalaryIntegrationField = value;
                    this.RaisePropertyChanged("CodeForSalaryIntegration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FlexPositiveFactor {
            get {
                return this.FlexPositiveFactorField;
            }
            set {
                if ((this.FlexPositiveFactorField.Equals(value) != true)) {
                    this.FlexPositiveFactorField = value;
                    this.RaisePropertyChanged("FlexPositiveFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTransferredToSalaryIntegration {
            get {
                return this.IsTransferredToSalaryIntegrationField;
            }
            set {
                if ((this.IsTransferredToSalaryIntegrationField.Equals(value) != true)) {
                    this.IsTransferredToSalaryIntegrationField = value;
                    this.RaisePropertyChanged("IsTransferredToSalaryIntegration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SalaryAccountFactor {
            get {
                return this.SalaryAccountFactorField;
            }
            set {
                if ((this.SalaryAccountFactorField.Equals(value) != true)) {
                    this.SalaryAccountFactorField = value;
                    this.RaisePropertyChanged("SalaryAccountFactor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.SalaryAccountFactorEffectTypes SalaryAccountFactorEffect {
            get {
                return this.SalaryAccountFactorEffectField;
            }
            set {
                if ((this.SalaryAccountFactorEffectField.Equals(value) != true)) {
                    this.SalaryAccountFactorEffectField = value;
                    this.RaisePropertyChanged("SalaryAccountFactorEffect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalaryAccountID {
            get {
                return this.SalaryAccountIDField;
            }
            set {
                if ((this.SalaryAccountIDField.Equals(value) != true)) {
                    this.SalaryAccountIDField = value;
                    this.RaisePropertyChanged("SalaryAccountID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.TimeTrackingFormat TimeTrackingFormat {
            get {
                return this.TimeTrackingFormatField;
            }
            set {
                if ((this.TimeTrackingFormatField.Equals(value) != true)) {
                    this.TimeTrackingFormatField = value;
                    this.RaisePropertyChanged("TimeTrackingFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public int AbsenceCodeID {
            get {
                return this.AbsenceCodeIDField;
            }
            set {
                if ((this.AbsenceCodeIDField.Equals(value) != true)) {
                    this.AbsenceCodeIDField = value;
                    this.RaisePropertyChanged("AbsenceCodeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int AbsenceCodeTypeID {
            get {
                return this.AbsenceCodeTypeIDField;
            }
            set {
                if ((this.AbsenceCodeTypeIDField.Equals(value) != true)) {
                    this.AbsenceCodeTypeIDField = value;
                    this.RaisePropertyChanged("AbsenceCodeTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool DeductCapacity {
            get {
                return this.DeductCapacityField;
            }
            set {
                if ((this.DeductCapacityField.Equals(value) != true)) {
                    this.DeductCapacityField = value;
                    this.RaisePropertyChanged("DeductCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public bool IsPublicVisible {
            get {
                return this.IsPublicVisibleField;
            }
            set {
                if ((this.IsPublicVisibleField.Equals(value) != true)) {
                    this.IsPublicVisibleField = value;
                    this.RaisePropertyChanged("IsPublicVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public bool RequireApproval {
            get {
                return this.RequireApprovalField;
            }
            set {
                if ((this.RequireApprovalField.Equals(value) != true)) {
                    this.RequireApprovalField = value;
                    this.RaisePropertyChanged("RequireApproval");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfNormalWorkingTime", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfNormalWorkingTime : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTime[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTime[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalWorkingTime", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Salary.V1_1")]
    [System.SerializableAttribute()]
    public partial class NormalWorkingTime : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CanBeDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTimeDay[] DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<int, double> NormHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormalWorkingTimeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTimeTypes NormalWorkingTimeTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanBeDeleted {
            get {
                return this.CanBeDeletedField;
            }
            set {
                if ((this.CanBeDeletedField.Equals(value) != true)) {
                    this.CanBeDeletedField = value;
                    this.RaisePropertyChanged("CanBeDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTimeDay[] Days {
            get {
                return this.DaysField;
            }
            set {
                if ((object.ReferenceEquals(this.DaysField, value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, double> NormHours {
            get {
                return this.NormHoursField;
            }
            set {
                if ((object.ReferenceEquals(this.NormHoursField, value) != true)) {
                    this.NormHoursField = value;
                    this.RaisePropertyChanged("NormHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalWorkingTimeID {
            get {
                return this.NormalWorkingTimeIDField;
            }
            set {
                if ((this.NormalWorkingTimeIDField.Equals(value) != true)) {
                    this.NormalWorkingTimeIDField = value;
                    this.RaisePropertyChanged("NormalWorkingTimeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.NormalWorkingTimeTypes NormalWorkingTimeType {
            get {
                return this.NormalWorkingTimeTypeField;
            }
            set {
                if ((this.NormalWorkingTimeTypeField.Equals(value) != true)) {
                    this.NormalWorkingTimeTypeField = value;
                    this.RaisePropertyChanged("NormalWorkingTimeType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalWorkingTimeDay", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Salary.V1_1")]
    [System.SerializableAttribute()]
    public partial class NormalWorkingTimeDay : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DayOfWeek DayOfWeekField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinutesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormalWorkingTimeDayIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormalWorkingTimeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DayOfWeek DayOfWeek {
            get {
                return this.DayOfWeekField;
            }
            set {
                if ((this.DayOfWeekField.Equals(value) != true)) {
                    this.DayOfWeekField = value;
                    this.RaisePropertyChanged("DayOfWeek");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Hours {
            get {
                return this.HoursField;
            }
            set {
                if ((this.HoursField.Equals(value) != true)) {
                    this.HoursField = value;
                    this.RaisePropertyChanged("Hours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Minutes {
            get {
                return this.MinutesField;
            }
            set {
                if ((this.MinutesField.Equals(value) != true)) {
                    this.MinutesField = value;
                    this.RaisePropertyChanged("Minutes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalWorkingTimeDayID {
            get {
                return this.NormalWorkingTimeDayIDField;
            }
            set {
                if ((this.NormalWorkingTimeDayIDField.Equals(value) != true)) {
                    this.NormalWorkingTimeDayIDField = value;
                    this.RaisePropertyChanged("NormalWorkingTimeDayID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NormalWorkingTimeID {
            get {
                return this.NormalWorkingTimeIDField;
            }
            set {
                if ((this.NormalWorkingTimeIDField.Equals(value) != true)) {
                    this.NormalWorkingTimeIDField = value;
                    this.RaisePropertyChanged("NormalWorkingTimeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfHolidayCalendar", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfHolidayCalendar : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.HolidayCalendar[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.HolidayCalendar[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HolidayCalendar", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Salary.V1_1")]
    [System.SerializableAttribute()]
    public partial class HolidayCalendar : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfAllowance", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfAllowance : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Allowance[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Allowance[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Allowance", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Salary.V1_1")]
    [System.SerializableAttribute()]
    public partial class Allowance : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_3")]
    [System.SerializableAttribute()]
    public partial class SecurityToken : TimeLog.TransactionalAPI.SDK.SalaryService.APIBase {
        
        private string InitialsField;
        
        private System.DateTime ExpiresField;
        
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionStatus", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Common")]
    public enum ExecutionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessage", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class APIMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalAPI.SDK.SalaryService.APIMessageSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalAPI.SDK.SalaryService.APIMessageSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryCodeSystemTypes", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Salary")]
    public enum SalaryCodeSystemTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NormalWorkingTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProjectTime = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryAccountFactorEffectTypes", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Salary")]
    public enum SalaryAccountFactorEffectTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Substract = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Add = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeTrackingFormat", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Salary")]
    public enum TimeTrackingFormat : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hours = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FullDay = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HalfDay = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YesNo = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Count = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalarySpecificationTypes", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Salary")]
    public enum SalarySpecificationTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalaryTime = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supplement = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaidOut = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestParameter", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class RequestParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessageSeverity", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_0")]
    public enum APIMessageSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalWorkingTimeTypes", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Employees")]
    public enum NormalWorkingTimeTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OneWeek = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoWeeks = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.timelog.com/api/tlp/v1_1", ConfigurationName="SalaryService.SalaryService")]
    public interface SalaryService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.timelog.com/api/tlp/v1_3) of message IsAliveRequest does not match the default value (http://www.timelog.com/api/tlp/v1_1)
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse IsAlive(TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse> IsAliveAsync(TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllSalaryCodes", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllSalaryCodesResponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfSalary GetAllSalaryCodes(TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeStatus salaryCodeStatus, TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllSalaryCodes", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllSalaryCodesResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfSalary> GetAllSalaryCodesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeStatus salaryCodeStatus, TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllAbsenceCodes", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllAbsenceCodesResponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAbsenceCode GetAllAbsenceCodes(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllAbsenceCodes", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllAbsenceCodesResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAbsenceCode> GetAllAbsenceCodesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetNormalWorkweeks", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetNormalWorkweeksResponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfNormalWorkingTime GetNormalWorkweeks(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetNormalWorkweeks", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetNormalWorkweeksResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfNormalWorkingTime> GetNormalWorkweeksAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetHolidayCalendars", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetHolidayCalendarsResponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfHolidayCalendar GetHolidayCalendars(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetHolidayCalendars", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetHolidayCalendarsResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfHolidayCalendar> GetHolidayCalendarsAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllowances", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllowancesResponse")]
        TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAllowance GetAllowances(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllowances", ReplyAction="http://www.timelog.com/api/tlp/v1_1/SalaryService/GetAllowancesResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAllowance> GetAllowancesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAlive", WrapperNamespace="http://www.timelog.com/api/tlp/v1_3", IsWrapped=true)]
    public partial class IsAliveRequest {
        
        public IsAliveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAliveResponse", WrapperNamespace="http://www.timelog.com/api/tlp/v1_3", IsWrapped=true)]
    public partial class IsAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.timelog.com/api/tlp/v1_3", Order=0)]
        public bool IsAliveResult;
        
        public IsAliveResponse() {
        }
        
        public IsAliveResponse(bool IsAliveResult) {
            this.IsAliveResult = IsAliveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalaryServiceChannel : TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalaryServiceClient : System.ServiceModel.ClientBase<TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService>, TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService {
        
        public SalaryServiceClient() {
        }
        
        public SalaryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalaryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService.IsAlive(TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest request) {
            return base.Channel.IsAlive(request);
        }
        
        public bool IsAlive() {
            TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest inValue = new TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest();
            TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse retVal = ((TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService)(this)).IsAlive(inValue);
            return retVal.IsAliveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse> TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService.IsAliveAsync(TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest request) {
            return base.Channel.IsAliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveResponse> IsAliveAsync() {
            TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest inValue = new TimeLog.TransactionalAPI.SDK.SalaryService.IsAliveRequest();
            return ((TimeLog.TransactionalAPI.SDK.SalaryService.SalaryService)(this)).IsAliveAsync(inValue);
        }
        
        public TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfSalary GetAllSalaryCodes(TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeStatus salaryCodeStatus, TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllSalaryCodes(salaryCodeStatus, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfSalary> GetAllSalaryCodesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SalaryCodeStatus salaryCodeStatus, TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllSalaryCodesAsync(salaryCodeStatus, token);
        }
        
        public TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAbsenceCode GetAllAbsenceCodes(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllAbsenceCodes(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAbsenceCode> GetAllAbsenceCodesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllAbsenceCodesAsync(token);
        }
        
        public TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfNormalWorkingTime GetNormalWorkweeks(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetNormalWorkweeks(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfNormalWorkingTime> GetNormalWorkweeksAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetNormalWorkweeksAsync(token);
        }
        
        public TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfHolidayCalendar GetHolidayCalendars(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetHolidayCalendars(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfHolidayCalendar> GetHolidayCalendarsAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetHolidayCalendarsAsync(token);
        }
        
        public TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAllowance GetAllowances(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllowances(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalAPI.SDK.SalaryService.ResponseOfAllowance> GetAllowancesAsync(TimeLog.TransactionalAPI.SDK.SalaryService.SecurityToken token) {
            return base.Channel.GetAllowancesAsync(token);
        }
    }
}
