//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeLog.TransactionalApi.SDK.FinancialService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIBase", Namespace="http://www.timelog.com/api/tlp/v1_2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.LegalEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.PriceGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.HourlyRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.EmployeeCostRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.Contract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.Payment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.Request))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPriceGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfHourlyRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfEmployeeCostRate))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfContract))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken))]
    public partial class APIBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegalEntity", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class LegalEntity : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LegalEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSystem {
            get {
                return this.IsSystemField;
            }
            set {
                if ((this.IsSystemField.Equals(value) != true)) {
                    this.IsSystemField = value;
                    this.RaisePropertyChanged("IsSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LegalEntityID {
            get {
                return this.LegalEntityIDField;
            }
            set {
                if ((this.LegalEntityIDField.Equals(value) != true)) {
                    this.LegalEntityIDField = value;
                    this.RaisePropertyChanged("LegalEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceGroup", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class PriceGroup : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LegalEntityIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName {
            get {
                return this.CurrencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNameField, value) != true)) {
                    this.CurrencyNameField = value;
                    this.RaisePropertyChanged("CurrencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISO {
            get {
                return this.ISOField;
            }
            set {
                if ((object.ReferenceEquals(this.ISOField, value) != true)) {
                    this.ISOField = value;
                    this.RaisePropertyChanged("ISO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LegalEntityID {
            get {
                return this.LegalEntityIDField;
            }
            set {
                if ((this.LegalEntityIDField.Equals(value) != true)) {
                    this.LegalEntityIDField = value;
                    this.RaisePropertyChanged("LegalEntityID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HourlyRate", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class HourlyRate : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HourlyRateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCustomerSpecificField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HourlyRateID {
            get {
                return this.HourlyRateIDField;
            }
            set {
                if ((this.HourlyRateIDField.Equals(value) != true)) {
                    this.HourlyRateIDField = value;
                    this.RaisePropertyChanged("HourlyRateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomerSpecific {
            get {
                return this.IsCustomerSpecificField;
            }
            set {
                if ((this.IsCustomerSpecificField.Equals(value) != true)) {
                    this.IsCustomerSpecificField = value;
                    this.RaisePropertyChanged("IsCustomerSpecific");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDefault {
            get {
                return this.IsDefaultField;
            }
            set {
                if ((this.IsDefaultField.Equals(value) != true)) {
                    this.IsDefaultField = value;
                    this.RaisePropertyChanged("IsDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSystem {
            get {
                return this.IsSystemField;
            }
            set {
                if ((this.IsSystemField.Equals(value) != true)) {
                    this.IsSystemField = value;
                    this.RaisePropertyChanged("IsSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeCostRate", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class EmployeeCostRate : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmployeeCostRateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmployeeCostRateId {
            get {
                return this.EmployeeCostRateIdField;
            }
            set {
                if ((this.EmployeeCostRateIdField.Equals(value) != true)) {
                    this.EmployeeCostRateIdField = value;
                    this.RaisePropertyChanged("EmployeeCostRateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contract", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class Contract : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContractIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContractID {
            get {
                return this.ContractIDField;
            }
            set {
                if ((this.ContractIDField.Equals(value) != true)) {
                    this.ContractIDField = value;
                    this.RaisePropertyChanged("ContractID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractType {
            get {
                return this.ContractTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractTypeField, value) != true)) {
                    this.ContractTypeField = value;
                    this.RaisePropertyChanged("ContractType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Financial.V1_2")]
    [System.SerializableAttribute()]
    public partial class Payment : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProjectSubContractIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((this.PaymentIDField.Equals(value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProjectID {
            get {
                return this.ProjectIDField;
            }
            set {
                if ((this.ProjectIDField.Equals(value) != true)) {
                    this.ProjectIDField = value;
                    this.RaisePropertyChanged("ProjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProjectSubContractID {
            get {
                return this.ProjectSubContractIDField;
            }
            set {
                if ((this.ProjectSubContractIDField.Equals(value) != true)) {
                    this.ProjectSubContractIDField = value;
                    this.RaisePropertyChanged("ProjectSubContractID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfLegalEntity", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfLegalEntity : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.LegalEntity[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.LegalEntity[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class Request : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.RequestParameter[] ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.RequestParameter[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceClass {
            get {
                return this.ServiceClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceClassField, value) != true)) {
                    this.ServiceClassField = value;
                    this.RaisePropertyChanged("ServiceClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string MethodName {
            get {
                return this.MethodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodNameField, value) != true)) {
                    this.MethodNameField = value;
                    this.RaisePropertyChanged("MethodName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfPriceGroup", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfPriceGroup : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.PriceGroup[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.PriceGroup[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfHourlyRate", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfHourlyRate : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.HourlyRate[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.HourlyRate[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfEmployeeCostRate", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfEmployeeCostRate : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.EmployeeCostRate[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.EmployeeCostRate[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfContract", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfContract : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Contract[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.Contract[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfPayment", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class ResponseOfPayment : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Payment[] ReturnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTypeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.Request RequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReturnPagedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalPageCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.Payment[] Return {
            get {
                return this.ReturnField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnField, value) != true)) {
                    this.ReturnField = value;
                    this.RaisePropertyChanged("Return");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnTypeDescription {
            get {
                return this.ReturnTypeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTypeDescriptionField, value) != true)) {
                    this.ReturnTypeDescriptionField = value;
                    this.RaisePropertyChanged("ReturnTypeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TimeLog.TransactionalApi.SDK.FinancialService.Request Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public TimeLog.TransactionalApi.SDK.FinancialService.ExecutionStatus ResponseState {
            get {
                return this.ResponseStateField;
            }
            set {
                if ((this.ResponseStateField.Equals(value) != true)) {
                    this.ResponseStateField = value;
                    this.RaisePropertyChanged("ResponseState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessage[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool IsReturnPaged {
            get {
                return this.IsReturnPagedField;
            }
            set {
                if ((this.IsReturnPagedField.Equals(value) != true)) {
                    this.IsReturnPagedField = value;
                    this.RaisePropertyChanged("IsReturnPaged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int TotalPageCount {
            get {
                return this.TotalPageCountField;
            }
            set {
                if ((this.TotalPageCountField.Equals(value) != true)) {
                    this.TotalPageCountField = value;
                    this.RaisePropertyChanged("TotalPageCount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityToken", Namespace="http://www.timelog.com/api/tlp/v1_3")]
    [System.SerializableAttribute()]
    public partial class SecurityToken : TimeLog.TransactionalApi.SDK.FinancialService.APIBase {
        
        private string InitialsField;
        
        private System.DateTime ExpiresField;
        
        private string HashField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Initials {
            get {
                return this.InitialsField;
            }
            set {
                if ((object.ReferenceEquals(this.InitialsField, value) != true)) {
                    this.InitialsField = value;
                    this.RaisePropertyChanged("Initials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Expires {
            get {
                return this.ExpiresField;
            }
            set {
                if ((this.ExpiresField.Equals(value) != true)) {
                    this.ExpiresField = value;
                    this.RaisePropertyChanged("Expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExecutionStatus", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.Common")]
    public enum ExecutionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessage", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class APIMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TimeLog.TransactionalApi.SDK.FinancialService.APIMessageSeverity SeverityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TimeLog.TransactionalApi.SDK.FinancialService.APIMessageSeverity Severity {
            get {
                return this.SeverityField;
            }
            set {
                if ((this.SeverityField.Equals(value) != true)) {
                    this.SeverityField = value;
                    this.RaisePropertyChanged("Severity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestParameter", Namespace="http://api.timelog.com")]
    [System.SerializableAttribute()]
    public partial class RequestParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIMessageSeverity", Namespace="http://schemas.datacontract.org/2004/07/TimeLog.TLP.API.Proxy.Communication.V1_0")]
    public enum APIMessageSeverity : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Message = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.timelog.com/api/tlp/v1_2", ConfigurationName="FinancialService.FinancialService")]
    public interface FinancialService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.timelog.com/api/tlp/v1_3) of message IsAliveRequest does not match the default value (http://www.timelog.com/api/tlp/v1_2)
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse IsAlive(TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="IsAliveRequest", ReplyAction="IsAliveReponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse> IsAliveAsync(TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntities", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesResponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntities(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntities", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesAsync(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByCurrency", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByCurrencyRe" +
            "sponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntitiesByCurrency(string currencyABB, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByCurrency", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByCurrencyRe" +
            "sponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesByCurrencyAsync(string currencyABB, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByName", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByNameRespon" +
            "se")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntitiesByName(string name, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByName", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetLegalEntitiesByNameRespon" +
            "se")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesByNameAsync(string name, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPriceGroups", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPriceGroupsResponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPriceGroup GetPriceGroups(System.Guid legalEntityID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPriceGroups", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPriceGroupsResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPriceGroup> GetPriceGroupsAsync(System.Guid legalEntityID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetHourlyRates", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetHourlyRatesResponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfHourlyRate GetHourlyRates(string currencyAbb, int legalEntityId, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetHourlyRates", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetHourlyRatesResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfHourlyRate> GetHourlyRatesAsync(string currencyAbb, int legalEntityId, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetEmployeeCostRates", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetEmployeeCostRatesResponse" +
            "")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfEmployeeCostRate GetEmployeeCostRates(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetEmployeeCostRates", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetEmployeeCostRatesResponse" +
            "")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfEmployeeCostRate> GetEmployeeCostRatesAsync(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetContractList", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetContractListResponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfContract GetContractList(int projectID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetContractList", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetContractListResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfContract> GetContractListAsync(int projectID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPaymentList", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPaymentListResponse")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment GetPaymentList(int contractID, System.DateTime startDate, System.DateTime endDate, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPaymentList", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/GetPaymentListResponse")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment> GetPaymentListAsync(int contractID, System.DateTime startDate, System.DateTime endDate, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/UpdatePaymentQuantity", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/UpdatePaymentQuantityRespons" +
            "e")]
        TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment UpdatePaymentQuantity(TimeLog.TransactionalApi.SDK.FinancialService.Payment payment, int source, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.timelog.com/api/tlp/v1_2/FinancialService/UpdatePaymentQuantity", ReplyAction="http://www.timelog.com/api/tlp/v1_2/FinancialService/UpdatePaymentQuantityRespons" +
            "e")]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment> UpdatePaymentQuantityAsync(TimeLog.TransactionalApi.SDK.FinancialService.Payment payment, int source, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAlive", WrapperNamespace="http://www.timelog.com/api/tlp/v1_3", IsWrapped=true)]
    public partial class IsAliveRequest {
        
        public IsAliveRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsAliveResponse", WrapperNamespace="http://www.timelog.com/api/tlp/v1_3", IsWrapped=true)]
    public partial class IsAliveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.timelog.com/api/tlp/v1_3", Order=0)]
        public bool IsAliveResult;
        
        public IsAliveResponse() {
        }
        
        public IsAliveResponse(bool IsAliveResult) {
            this.IsAliveResult = IsAliveResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinancialServiceChannel : TimeLog.TransactionalApi.SDK.FinancialService.FinancialService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialServiceClient : System.ServiceModel.ClientBase<TimeLog.TransactionalApi.SDK.FinancialService.FinancialService>, TimeLog.TransactionalApi.SDK.FinancialService.FinancialService {
        
        public FinancialServiceClient() {
        }
        
        public FinancialServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse TimeLog.TransactionalApi.SDK.FinancialService.FinancialService.IsAlive(TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest request) {
            return base.Channel.IsAlive(request);
        }
        
        public bool IsAlive() {
            TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest inValue = new TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest();
            TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse retVal = ((TimeLog.TransactionalApi.SDK.FinancialService.FinancialService)(this)).IsAlive(inValue);
            return retVal.IsAliveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse> TimeLog.TransactionalApi.SDK.FinancialService.FinancialService.IsAliveAsync(TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest request) {
            return base.Channel.IsAliveAsync(request);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.IsAliveResponse> IsAliveAsync() {
            TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest inValue = new TimeLog.TransactionalApi.SDK.FinancialService.IsAliveRequest();
            return ((TimeLog.TransactionalApi.SDK.FinancialService.FinancialService)(this)).IsAliveAsync(inValue);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntities(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntities(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesAsync(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntitiesAsync(token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntitiesByCurrency(string currencyABB, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntitiesByCurrency(currencyABB, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesByCurrencyAsync(string currencyABB, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntitiesByCurrencyAsync(currencyABB, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity GetLegalEntitiesByName(string name, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntitiesByName(name, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfLegalEntity> GetLegalEntitiesByNameAsync(string name, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetLegalEntitiesByNameAsync(name, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPriceGroup GetPriceGroups(System.Guid legalEntityID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetPriceGroups(legalEntityID, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPriceGroup> GetPriceGroupsAsync(System.Guid legalEntityID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetPriceGroupsAsync(legalEntityID, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfHourlyRate GetHourlyRates(string currencyAbb, int legalEntityId, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetHourlyRates(currencyAbb, legalEntityId, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfHourlyRate> GetHourlyRatesAsync(string currencyAbb, int legalEntityId, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetHourlyRatesAsync(currencyAbb, legalEntityId, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfEmployeeCostRate GetEmployeeCostRates(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetEmployeeCostRates(token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfEmployeeCostRate> GetEmployeeCostRatesAsync(TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetEmployeeCostRatesAsync(token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfContract GetContractList(int projectID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetContractList(projectID, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfContract> GetContractListAsync(int projectID, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetContractListAsync(projectID, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment GetPaymentList(int contractID, System.DateTime startDate, System.DateTime endDate, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetPaymentList(contractID, startDate, endDate, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment> GetPaymentListAsync(int contractID, System.DateTime startDate, System.DateTime endDate, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.GetPaymentListAsync(contractID, startDate, endDate, token);
        }
        
        public TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment UpdatePaymentQuantity(TimeLog.TransactionalApi.SDK.FinancialService.Payment payment, int source, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.UpdatePaymentQuantity(payment, source, token);
        }
        
        public System.Threading.Tasks.Task<TimeLog.TransactionalApi.SDK.FinancialService.ResponseOfPayment> UpdatePaymentQuantityAsync(TimeLog.TransactionalApi.SDK.FinancialService.Payment payment, int source, TimeLog.TransactionalApi.SDK.FinancialService.SecurityToken token) {
            return base.Channel.UpdatePaymentQuantityAsync(payment, source, token);
        }
    }
}
